name: ci # я придумал сам
on:
  push:
    branches:
      - master
      - main
jobs:
  package: # я придумал сам
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # скопирует репозиторий на эту машинку
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: mvn package # run - если пишем свою команду, а не готовый чей-то action

